# Generated by Django 4.0.1 on 2022-02-01 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('HTML', 'HTML5'), ('CSS3', 'CSS3'), ('SASS', 'SASS'), ('JASC', 'JavaScript'), ('PYTH', 'Python'), ('DJAN', 'Django'), ('RUBY', 'Ruby'), ('RAIL', 'Ruby on Rails')], max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('project_type', models.CharField(choices=[('DES', 'Design'), ('DEV', 'Development')], default='DEV', max_length=3)),
                ('about', models.TextField()),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('PS', 'Photoshop'), ('AI', 'Illustrator')], max_length=2)),
            ],
            options={
                'verbose_name_plural': 'Software',
            },
        ),
        migrations.CreateModel(
            name='Developemnt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/dev/')),
                ('description', models.TextField()),
                ('programs', models.ManyToManyField(to='jvc_portfolio.Program')),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/des/')),
                ('description', models.TextField()),
                ('software', models.ManyToManyField(to='jvc_portfolio.Software')),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
    ]
