# Generated by Django 4.0.1 on 2022-02-01 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jvc_portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Developemnt',
            new_name='Developement',
        ),
    ]
