# Generated by Django 4.0.2 on 2022-09-14 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jvc_portfolio', '0002_project_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='design',
            name='description',
        ),
        migrations.AddField(
            model_name='design',
            name='brief',
            field=models.TextField(blank=True, db_column='description', null=True),
        ),
        migrations.AddField(
            model_name='design',
            name='project_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='design',
            name='sub_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
