# Generated by Django 4.0.1 on 2022-02-02 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jvc_portfolio', '0002_rename_developemnt_developement'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Developement',
            new_name='Development',
        ),
    ]
