# Generated by Django 4.0.2 on 2022-09-14 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jvc_portfolio', '0003_remove_design_description_design_brief_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='design',
            old_name='image',
            new_name='banner_img',
        ),
        migrations.AlterField(
            model_name='design',
            name='banner_img',
            field=models.ImageField(blank=True, db_column='image', null=True, upload_to='images/des/'),
        ),
    ]
