# Generated by Django 4.0.2 on 2022-09-14 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jvc_portfolio', '0005_design_asset_imgi_design_asset_imgii_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='design',
            old_name='banner_txt',
            new_name='banner_txtI',
        ),
        migrations.RenameField(
            model_name='design',
            old_name='process',
            new_name='processI',
        ),
        migrations.RenameField(
            model_name='design',
            old_name='process_cont',
            new_name='process_contI',
        ),
        migrations.AddField(
            model_name='design',
            name='banner_txtII',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='design',
            name='banner_txtIII',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='design',
            name='processII',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='design',
            name='processIII',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='design',
            name='process_contII',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='design',
            name='process_contIII',
            field=models.TextField(blank=True, null=True),
        ),
    ]
