# Generated by Django 4.0.1 on 2022-02-04 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jvc_portfolio', '0005_alter_software_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='software',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
