# Generated by Django 4.0.2 on 2022-09-14 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jvc_portfolio', '0006_rename_banner_txt_design_banner_txti_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='design',
            old_name='process_contI',
            new_name='processIV',
        ),
        migrations.RenameField(
            model_name='design',
            old_name='process_contII',
            new_name='processV',
        ),
        migrations.RenameField(
            model_name='design',
            old_name='process_contIII',
            new_name='processVI',
        ),
    ]
