# Generated by Django 4.0.2 on 2023-11-14 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jvc_portfolio', '0007_rename_process_conti_design_processiv_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
    ]
