# Generated by Django 4.0.2 on 2023-11-20 19:39

from django.db import migrations, models
import jvc_portfolio.models


class Migration(migrations.Migration):

    dependencies = [
        ('jvc_portfolio', '0010_project_banner_texti_project_banner_textii_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='asset_imgI',
            field=models.ImageField(blank=True, null=True, upload_to=jvc_portfolio.models.project_path),
        ),
        migrations.AddField(
            model_name='project',
            name='asset_imgII',
            field=models.ImageField(blank=True, null=True, upload_to=jvc_portfolio.models.project_path),
        ),
        migrations.AddField(
            model_name='project',
            name='asset_imgIII',
            field=models.ImageField(blank=True, null=True, upload_to=jvc_portfolio.models.project_path),
        ),
        migrations.AddField(
            model_name='project',
            name='conclusion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='fullpage_imgII',
            field=models.ImageField(blank=True, null=True, upload_to=jvc_portfolio.models.project_path),
        ),
        migrations.AddField(
            model_name='project',
            name='fullpage_imgIII',
            field=models.ImageField(blank=True, null=True, upload_to=jvc_portfolio.models.project_path),
        ),
        migrations.AddField(
            model_name='project',
            name='mockup_imgI',
            field=models.ImageField(blank=True, null=True, upload_to=jvc_portfolio.models.project_path),
        ),
        migrations.AddField(
            model_name='project',
            name='mockup_imgII',
            field=models.ImageField(blank=True, null=True, upload_to=jvc_portfolio.models.project_path),
        ),
        migrations.AddField(
            model_name='project',
            name='mockup_imgIII',
            field=models.ImageField(blank=True, null=True, upload_to=jvc_portfolio.models.project_path),
        ),
        migrations.AddField(
            model_name='project',
            name='processI',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='processII',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='processIII',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='processIV',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='processV',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='processVI',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='programs',
            field=models.ManyToManyField(blank=True, to='jvc_portfolio.Program'),
        ),
        migrations.AddField(
            model_name='project',
            name='responsive_imgI',
            field=models.ImageField(blank=True, null=True, upload_to=jvc_portfolio.models.project_path),
        ),
        migrations.AddField(
            model_name='project',
            name='responsive_imgII',
            field=models.ImageField(blank=True, null=True, upload_to=jvc_portfolio.models.project_path),
        ),
        migrations.AddField(
            model_name='project',
            name='responsive_imgIII',
            field=models.ImageField(blank=True, null=True, upload_to=jvc_portfolio.models.project_path),
        ),
        migrations.AddField(
            model_name='project',
            name='software',
            field=models.ManyToManyField(blank=True, to='jvc_portfolio.Software'),
        ),
    ]
