# Generated by Django 4.0.2 on 2023-11-21 21:25

from django.db import migrations, models
import jvc_portfolio.models


class Migration(migrations.Migration):

    dependencies = [
        ('jvc_portfolio', '0011_project_asset_imgi_project_asset_imgii_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='fullpage_imgIV',
            field=models.ImageField(blank=True, null=True, upload_to=jvc_portfolio.models.project_path),
        ),
        migrations.AddField(
            model_name='project',
            name='fullpage_imgV',
            field=models.ImageField(blank=True, null=True, upload_to=jvc_portfolio.models.project_path),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(blank=True, choices=[('DES', 'Design'), ('DEV', 'Development')], default='DEV', max_length=3, null=True),
        ),
    ]
