# Generated by Django 4.0.2 on 2023-11-21 21:46

from django.db import migrations, models
import jvc_portfolio.models


class Migration(migrations.Migration):

    dependencies = [
        ('jvc_portfolio', '0012_project_fullpage_imgiv_project_fullpage_imgv_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='fullpage_imgIX',
            field=models.ImageField(blank=True, null=True, upload_to=jvc_portfolio.models.project_path),
        ),
        migrations.AddField(
            model_name='project',
            name='fullpage_imgVI',
            field=models.ImageField(blank=True, null=True, upload_to=jvc_portfolio.models.project_path),
        ),
        migrations.AddField(
            model_name='project',
            name='fullpage_imgVII',
            field=models.ImageField(blank=True, null=True, upload_to=jvc_portfolio.models.project_path),
        ),
        migrations.AddField(
            model_name='project',
            name='fullpage_imgVIII',
            field=models.ImageField(blank=True, null=True, upload_to=jvc_portfolio.models.project_path),
        ),
        migrations.AddField(
            model_name='project',
            name='fullpage_imgX',
            field=models.ImageField(blank=True, null=True, upload_to=jvc_portfolio.models.project_path),
        ),
        migrations.AddField(
            model_name='project',
            name='processIX',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='processVII',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='processVIII',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='processX',
            field=models.TextField(blank=True, null=True),
        ),
    ]
