# Generated by Django 4.0.2 on 2023-11-16 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jvc_resume', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplimentaleducation',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
