# Generated by Django 4.0.2 on 2023-12-01 18:14

from django.db import migrations, models
import jvc_resume.models


class Migration(migrations.Migration):

    dependencies = [
        ('jvc_resume', '0003_about_updated_on_alter_employment_job_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=jvc_resume.models.bio_path),
        ),
    ]
