# Generated by Django 4.0.2 on 2023-12-05 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jvc_resume', '0004_about_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='employment',
            name='end_year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='employment',
            name='start_year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='employment',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
