# Generated by Django 4.0.2 on 2024-02-14 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jvc_resume', '0005_employment_end_year_employment_start_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='header',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
