# Generated by Django 4.0.2 on 2024-02-14 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jvc_resume', '0006_about_header'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
